# These are supported funding model platforms
## ☕ Support This Project
🇬🇭 Paystack (Mobile Money & cards): [paystack.com/pay/Elmejor_Austin](#)  
🌍 Buy Me a Coffee (Stripe & PayPal): [buymeacoffee.com/elmejor](#)


custom: custom: ['https://paystack.com/pay/Elmejor_austin']
